# Generated by Django 3.2.9 on 2021-11-19 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_recommend_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommend_list',
            name='products',
        ),
        migrations.AddField(
            model_name='recommend_list',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, to='myapp.Product'),
        ),
    ]
