# Generated by Django 3.2.9 on 2021-11-19 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_recommend_list_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommend_list',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
