# Generated by Django 3.2.9 on 2021-11-19 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_recommend_list_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recommend_list',
        ),
    ]
