# Generated by Django 3.2.9 on 2021-11-19 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_reccom'),
    ]

    operations = [
        migrations.AddField(
            model_name='reccom',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
