# Generated by Django 3.2.9 on 2021-12-19 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_auto_20211219_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='showcase',
        ),
        migrations.AddField(
            model_name='product',
            name='showcase',
            field=models.ManyToManyField(to='myapp.Showcase'),
        ),
    ]
